Change filenames in SFC/svg/png
Shinimah/shop-pm pull request #17
Opened 2022-11-30 09:28 UTC by Shinimah

Close #1

2022-11-30 11:05 UTC, pavel-nyukalo requested changes

2022-11-30 11:05 UTC, pavel-nyukalo commented on src/components/ProductItem.vue
> +        }
Это был пример работы с медиа запросами, в мастер его не надо

2022-11-30 11:57 UTC, khatskelevich approved these changes

2022-12-05 04:58 UTC, pavel-nyukalo approved these changes

2022-12-05 06:08 UTC, merged