fixed button, link & img in HTML
Shinimah/shop-pm pull request #20
Opened 2022-11-30 12:15 UTC by Shinimah

Close #6

2022-12-01 13:25 UTC, khatskelevich approved these changes

2022-12-05 05:02 UTC, pavel-nyukalo requested changes

2022-12-05 05:02 UTC, pavel-nyukalo commented on src/App.vue
> +    <img id="logo" src="./icons/Group1.svg" alt="logo"/>
У всех картинок проверил наличие `alt`?
Или в проекте только одна картинка вставлена через `img`?

2022-12-05 05:02 UTC, pavel-nyukalo commented on src/components/CompTwo.vue
> +                <div class="btn">
Потом когда будешь править семантику, я бы предложил подумать, а нужен ли нам этот `div`?  
По сути он просто оборачивает `select` и в таком случае мы можем сразу стилизовать `select`

2022-12-05 05:51 UTC, Shinimah commented on src/components/CompTwo.vue
> +                <div class="btn">
две только, их поправил.
остальные - через интерфейсы и svg

2022-12-05 10:22 UTC, pavel-nyukalo approved these changes

2022-12-05 10:49 UTC, merged