created head-component, cleaned app.vue
Shinimah/shop-pm pull request #21
Opened 2022-11-30 13:25 UTC by Shinimah

Close #9

2022-12-01 13:27 UTC, khatskelevich requested changes

2022-12-01 13:27 UTC, khatskelevich commented on src/App.vue
> +  <HeadTitle />
У тебя в этом компоненте содержится навигация. Семантически правильнее назвать этот компонент `Navigation`

2022-12-01 13:28 UTC, khatskelevich requested changes

2022-12-01 13:28 UTC, khatskelevich commented on src/components/HeadTitle.vue
> +    display: ruby;
ты же только избавился от этих свойств, а они снова здесь:(

2022-12-02 05:20 UTC, Shinimah commented on src/components/HeadTitle.vue
> +    display: ruby;
это в другой ветке, она пока не добавлена

2022-12-05 05:03 UTC, pavel-nyukalo approved these changes

2022-12-06 08:06 UTC, khatskelevich approved these changes

2022-12-08 07:04 UTC, merged