Semantic html
Shinimah/shop-pm pull request #23
Opened 2022-12-05 08:07 UTC by Shinimah

Close #10

2022-12-06 08:07 UTC, khatskelevich approved these changes

2022-12-07 09:35 UTC, pavel-nyukalo requested changes

2022-12-07 09:35 UTC, pavel-nyukalo commented on src/components/CategoryItem.vue
> +                    <div class="item-title">
Если это заголовок (судя по классу), более семантично будет здесь сделать тег заголовка (h1-h6)

2022-12-07 09:35 UTC, pavel-nyukalo commented on src/components/HeadTitle.vue
> +    <p class="title">Shopka</p>
Тут тоже по всей видимости заголовок

2022-12-07 09:35 UTC, pavel-nyukalo commented on src/components/HeadTitle.vue
> +    >
Кстати, кнопкам лучше в явном виде прописывать `type`. По-умолчанию он `submit`, и это иногда может выстрелить в ногу

2022-12-07 09:35 UTC, pavel-nyukalo commented on src/components/MenuHead.vue
> +  </button>
`p` нельзя вкладывать в `button`

![image](https://user-images.githubusercontent.com/52506235/206141641-7e8e585a-6792-43cf-88e5-4483df79e8d9.png)

Можно заменить на `span`

2022-12-07 09:35 UTC, pavel-nyukalo commented on src/components/ProductHead.vue
> +                <div class="btn">
Нужна ли эта обертка `select`? Мы можем стилизовать сразу `select`

2022-12-07 09:35 UTC, pavel-nyukalo commented on src/views/HomeView.vue
>      <div class="main">
Можно на `section` заменить

2022-12-08 07:33 UTC, merged

2022-12-08 09:01 UTC, Shinimah commented on src/components/ProductHead.vue
> +                <div class="btn">
в предыдущих пулах поправил...